# Generated by Django 3.1.6 on 2021-02-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Author',
            new_name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
