# Generated by Django 3.1.6 on 2021-03-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0006_auto_20210303_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nick_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
