# Generated by Django 3.1.6 on 2021-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0010_remove_category_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nick_name',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
